# Base image
FROM python:3.11-alpine AS base

ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Dependencies
RUN apk add --no-cache ffmpeg

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Application
FROM base AS production

WORKDIR /app

COPY ./src ./src
COPY ./worker ./worker
COPY ./videos/nba-rs-normalized.mp4 ./videos/nba-rs-normalized.mp4

CMD ["python", "-m", "worker.video_processor_task"]